#!/usr/bin/env bash

#
# == dist script ==
#
# Bundle up `bak` for:
#  * Debian        - .DEB
#  * RedHat        - .RPM
#  * Arch Linux    - .pkg.tar.zst
#  * Alpine Linux  - .apk
#  * Snap          - .snap
#  * FreeBSD       - .freebsd
#  * MacOS         - .pkg
#  * Generic       - .tar.gz
#
# Run from project root please!
# WARNING: The scripts in this folder are written specifically to run on MacOS [via Github Actions]
#

# NOTE: Most of the FPM options can be found it the .fpm file in the root of the project.

# Ensure the `dist` directory exists
rm -rf dist
mkdir -p dist

# Debian
fpm \
	-t deb \
	-p dist/bak-$(cat version)-1-any.deb \
	--version $(cat version) \
	--deb-changelog changelog.md

# RedHat
fpm \
	-t rpm \
	-p dist/bak-$(cat version)-1-any.rpm \
	--version $(cat version) \
	--rpm-changelog changelog.md

# Arch Linux
fpm \
	-t pacman \
	-p dist/bak-$(cat version)-1-any.pkg.tar.zst \
	--version $(cat version)

# Alpine Linux
fpm \
	-t apk \
	-p dist/bak-$(cat version)-1-any.apk \
	--version $(cat version)

# Snap
fpm \
	-t snap \
	-p dist/bak-$(cat version)-1-any.snap \
	--version $(cat version)

# FreeBSD
fpm \
	-t freebsd \
	-p dist/bak-$(cat version)-1-any.freebsd \
	--version $(cat version)

# MacOS
fpm \
	-t osxpkg \
	-p dist/bak-$(cat version)-1-any.pkg \
	--version $(cat version)

# Generic
tar -czf dist/bak-$(cat version)-1-any.tar.gz man source changelog.md license.md readme.md version
